name: cam_of_ball
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

##############################################################################################################################
### Scripts
scripts:
  # run is a default script. To use it, simply type
  # in the command line: "rps" - that's all!
  model_build: "dart run build_runner build --delete-conflicting-outputs"

  clean_get: "flutter clean && flutter pub get"

### Scripts
##############################################################################################################################
environment:
  sdk: '>=3.1.0 <4.0.0'
##############################################################################################################################
###
### Dependencies
###
dependencies:
  cookie_jar: ^4.0.8
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  envied: ^0.3.0+3
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  injectable: ^2.3.0
  internet_connection_checker: ^1.0.0+1
  stacked: ^3.4.1
  auto_route: ^7.8.3
  flutter_svg: ^2.0.7
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  flutter_staggered_grid_view: ^0.7.0
  card_swiper: ^3.0.1
  gradient_slider: ^1.0.1
  
  

###
### Dependencies
###
##############################################################################################################################
##############################################################################################################################
###
### Dev Dependencies
###
dev_dependencies:
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.1

  ###
  ### Lint
  ###
  envied_generator: ^0.3.0+3
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

  ###
  ### Injection Generator
  ###
  injectable_generator: ^2.4.0

  ###
  ### Json Serialization
  ###
  json_serializable: ^6.7.1
  freezed: ^2.4.1
  very_good_analysis: ^5.1.0
###
### Dev Dependencies
###
##############################################################################################################################
flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/png/
    - assets/png/register/
    - assets/png/images/
    - assets/svg/home_screen/bottom_navigator_bar/
    - assets/svg/home_screen/home_screen/
    - assets/svg/shop_screen/
    - assets/svg/chat/
    - assets/svg/profil_screen/
    - assets/svg/notification/
    - assets/svg/onboarding/
    - assets/svg/login/
    - assets/svg/register/
    - assets/svg/icon/
    - test/fixtures/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
